### ISSUE TITLE
The command 'py -3 __init__.py -h' brings up an error

### ISSUE THREAD

**Issue by De-x** [davFaithid/pokemon-tv#3]
When I used the command 'py -3 __init__.py -h' the message "Traceback (most recent call last):
  File "C:\Users\rakin\Documents\pokemon-tv-0.2\pokemon-tv\__init__.py", line 27, in <module>
    import mpv
  File "C:\Users\rakin\AppData\Local\Programs\Python\Python39\lib\site-packages\mpv.py", line 37, in <module>
    backend = CDLL(dll)
  File "C:\Users\rakin\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application" comes up. I did all the steps and placed mpv-1.dll in the python folder. I'm using command prompt on windows terminal for all of this. The only thing that I think might cause this is maybe me not having libmpv but I don't even know how to install libmpv but I did download the mpv github which has a folder called libmpv. But I have every dependency otherwise.

**Comment by De-x** [comment]
By the way I was in the directory pokemon tv with the __init__.py file. And I also only moved the mpv-1.dll file and nothing else. I am also not using the OneDrive documents folder but instead the non-OneDrive documents folder

**Comment by De-x** [comment]
I tried on fedora linux and I got to the step of the pokemon tv season number episode number message. When I did the command "py -3 __init__.py 1 1" or anything else, I got a message saying "Video is not available for playback." This might be due to the fact that the laptop I was trying this on is much more underpowered than what I'm currently running but I was able to run other things in mpv.
